spring.application.name=demo

# mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/spring_sec_tutorial?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.url=jdbc:mysql://localhost:3306/your_database?useSSL=true // for production
spring.datasource.username=brian
spring.datasource.password=password
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# # test user
# spring.security.user.name=user
# spring.security.user.password=password
#spring.security.user.roles=USER